[package]
name = "disk-destroyer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
signal-hook = "0.3.17"
getopts = "0.2.21"
path-clean = "1.0.1"
shellexpand = "3.1.0"
